<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { orderApi } from '@/apis/backend'
import type { OrderDetail, OrderSummary } from '@/types/backend'
import { useUserStore } from '@/stores/user'

const userStore=useUserStore(); const canWrite=userStore.hasAuthority('order:write')
const loading=ref(false); const rows=ref<OrderSummary[]>([]); const total=ref(0)
const query=reactive({orderSn:'',memberId:undefined as number|undefined,status:undefined as number|undefined,pageNum:1,pageSize:10})
const detailVisible=ref(false); const detail=ref<OrderDetail>()
const shipVisible=ref(false); const shippingId=ref<number>(); const shipForm=reactive({deliveryCompany:'',deliverySn:''})
async function load(){loading.value=true;try{const res=await orderApi.page(query);rows.value=res.data.list;total.value=res.data.total}finally{loading.value=false}}
async function showDetail(row:OrderSummary){detail.value=(await orderApi.detail(row.orderId)).data;detailVisible.value=true}
function openShip(row:OrderSummary){shippingId.value=row.orderId;shipForm.deliveryCompany='';shipForm.deliverySn='';shipVisible.value=true}
async function ship(){if(!shippingId.value||!shipForm.deliveryCompany.trim()||!shipForm.deliverySn.trim())return ElMessage.warning('请填写物流公司和物流单号');await orderApi.ship(shippingId.value,shipForm);ElMessage.success('发货成功');shipVisible.value=false;await load()}
onMounted(load)
</script>
<template><div class="page"><el-card><div class="toolbar"><el-input v-model="query.orderSn" clearable placeholder="订单号"/><el-input-number v-model="query.memberId" :min="1" controls-position="right" placeholder="会员ID"/><el-select v-model="query.status" clearable placeholder="订单状态"><el-option v-for="(name,index) in ['待支付','待发货','已发货','已完成','已取消','退款处理中','已退款']" :key="index" :label="name" :value="index"/></el-select><el-button type="primary" @click="query.pageNum=1;load()">查询</el-button></div>
<el-table v-loading="loading" :data="rows" border><el-table-column prop="orderSn" label="订单号" min-width="190"/><el-table-column prop="memberId" label="会员ID" width="90"/><el-table-column prop="firstProductName" label="商品" min-width="150"/><el-table-column prop="totalQuantity" label="数量" width="70"/><el-table-column prop="payAmount" label="支付金额" width="110"/><el-table-column prop="statusDescription" label="状态" width="110"/><el-table-column prop="receiverName" label="收货人" width="100"/><el-table-column prop="createTime" label="下单时间" width="180"/><el-table-column label="操作" width="150" fixed="right"><template #default="{row}"><el-button link type="primary" @click="showDetail(row)">详情</el-button><el-button v-if="canWrite&&row.status===1" link type="success" @click="openShip(row)">发货</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="query.pageNum" v-model:page-size="query.pageSize" :total="total" layout="total, sizes, prev, pager, next" @change="load"/></el-card>
<el-dialog v-model="detailVisible" title="订单详情" width="900px"><template v-if="detail"><el-descriptions :column="3" border><el-descriptions-item label="订单号">{{detail.orderSn}}</el-descriptions-item><el-descriptions-item label="会员ID">{{detail.memberId}}</el-descriptions-item><el-descriptions-item label="状态">{{detail.statusDescription}}</el-descriptions-item><el-descriptions-item label="总金额">￥{{detail.totalAmount}}</el-descriptions-item><el-descriptions-item label="支付金额">￥{{detail.payAmount}}</el-descriptions-item><el-descriptions-item label="创建时间">{{detail.createTime}}</el-descriptions-item><el-descriptions-item label="收货地址" :span="3">{{detail.receiver.province}}{{detail.receiver.city}}{{detail.receiver.region}}{{detail.receiver.detailAddress}}（{{detail.receiver.name}} {{detail.receiver.phone}}）</el-descriptions-item><el-descriptions-item label="物流" :span="3">{{detail.delivery.deliveryCompany||'-'}} {{detail.delivery.deliverySn||''}}</el-descriptions-item><el-descriptions-item label="备注" :span="3">{{detail.note||'-'}}</el-descriptions-item></el-descriptions><el-table :data="detail.items" border style="margin-top:16px"><el-table-column prop="productName" label="商品"/><el-table-column prop="skuCode" label="SKU"/><el-table-column prop="specData" label="规格"/><el-table-column prop="productPrice" label="单价"/><el-table-column prop="quantity" label="数量"/><el-table-column prop="subtotal" label="小计"/></el-table></template></el-dialog>
<el-dialog v-model="shipVisible" title="订单发货" width="500px"><el-form :model="shipForm" label-width="100px"><el-form-item label="物流公司" required><el-input v-model="shipForm.deliveryCompany"/></el-form-item><el-form-item label="物流单号" required><el-input v-model="shipForm.deliverySn"/></el-form-item></el-form><template #footer><el-button @click="shipVisible=false">取消</el-button><el-button type="primary" @click="ship">确认发货</el-button></template></el-dialog></div></template>
<style scoped>.page{padding:20px}.toolbar{display:flex;gap:10px;margin-bottom:16px}.toolbar .el-input,.toolbar .el-select{width:200px}.el-pagination{margin-top:16px;justify-content:flex-end}</style>
