<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { refundApi } from '@/apis/backend'
import type { Refund } from '@/types/backend'
import { useUserStore } from '@/stores/user'

const userStore=useUserStore();const canWrite=userStore.hasAuthority('refund:write')
const loading=ref(false);const rows=ref<Refund[]>([]);const total=ref(0)
const query=reactive({refundSn:'',orderSn:'',memberId:undefined as number|undefined,status:undefined as number|undefined,pageNum:1,pageSize:10})
const detailVisible=ref(false);const detail=ref<Refund>()
const auditVisible=ref(false);const auditMode=ref<'approve'|'reject'>('approve');const auditing=ref<Refund>();const adminNote=ref('')
async function load(){loading.value=true;try{const res=await refundApi.page(query);rows.value=res.data.list;total.value=res.data.total}finally{loading.value=false}}
async function showDetail(row:Refund){detail.value=(await refundApi.detail(row.refundId)).data;detailVisible.value=true}
function openAudit(row:Refund,mode:'approve'|'reject'){auditing.value=row;auditMode.value=mode;adminNote.value='';auditVisible.value=true}
async function audit(){if(!auditing.value)return;if(auditMode.value==='reject'&&!adminNote.value.trim())return ElMessage.warning('请填写拒绝原因');if(auditMode.value==='approve')await refundApi.approve(auditing.value.refundId,adminNote.value||undefined);else await refundApi.reject(auditing.value.refundId,adminNote.value);ElMessage.success('退款审核完成');auditVisible.value=false;await load()}
onMounted(load)
</script>
<template><div class="page"><el-card><div class="toolbar"><el-input v-model="query.refundSn" clearable placeholder="退款单号"/><el-input v-model="query.orderSn" clearable placeholder="订单号"/><el-select v-model="query.status" clearable placeholder="状态"><el-option label="待审核" :value="0"/><el-option label="已退款" :value="1"/><el-option label="已拒绝" :value="2"/></el-select><el-button type="primary" @click="query.pageNum=1;load()">查询</el-button></div><el-table v-loading="loading" :data="rows" border><el-table-column prop="refundSn" label="退款单号" min-width="190"/><el-table-column prop="orderSn" label="订单号" min-width="190"/><el-table-column prop="memberId" label="会员ID" width="90"/><el-table-column prop="refundAmount" label="退款金额" width="110"/><el-table-column prop="reason" label="原因" min-width="150"/><el-table-column prop="statusDescription" label="状态" width="100"/><el-table-column prop="createTime" label="申请时间" width="180"/><el-table-column label="操作" width="190" fixed="right"><template #default="{row}"><el-button link type="primary" @click="showDetail(row)">详情</el-button><template v-if="canWrite&&row.status===0"><el-button link type="success" @click="openAudit(row,'approve')">通过</el-button><el-button link type="danger" @click="openAudit(row,'reject')">拒绝</el-button></template></template></el-table-column></el-table><el-pagination v-model:current-page="query.pageNum" v-model:page-size="query.pageSize" :total="total" layout="total, sizes, prev, pager, next" @change="load"/></el-card>
<el-dialog v-model="detailVisible" title="退款详情" width="700px"><el-descriptions v-if="detail" :column="2" border><el-descriptions-item label="退款单号">{{detail.refundSn}}</el-descriptions-item><el-descriptions-item label="订单号">{{detail.orderSn}}</el-descriptions-item><el-descriptions-item label="会员ID">{{detail.memberId}}</el-descriptions-item><el-descriptions-item label="退款金额">￥{{detail.refundAmount}}</el-descriptions-item><el-descriptions-item label="状态">{{detail.statusDescription}}</el-descriptions-item><el-descriptions-item label="处理时间">{{detail.handleTime||'-'}}</el-descriptions-item><el-descriptions-item label="申请原因" :span="2">{{detail.reason}}</el-descriptions-item><el-descriptions-item label="管理员备注" :span="2">{{detail.adminNote||'-'}}</el-descriptions-item></el-descriptions></el-dialog>
<el-dialog v-model="auditVisible" :title="auditMode==='approve'?'通过退款':'拒绝退款'" width="520px"><el-form label-width="100px"><el-form-item :label="auditMode==='approve'?'审核备注':'拒绝原因'" :required="auditMode==='reject'"><el-input v-model="adminNote" type="textarea" :rows="4"/></el-form-item></el-form><template #footer><el-button @click="auditVisible=false">取消</el-button><el-button :type="auditMode==='approve'?'success':'danger'" @click="audit">确认</el-button></template></el-dialog></div></template>
<style scoped>.page{padding:20px}.toolbar{display:flex;gap:10px;margin-bottom:16px}.toolbar .el-input,.toolbar .el-select{width:190px}.el-pagination{margin-top:16px;justify-content:flex-end}</style>
