@baseUrl = http://localhost:8080
@password = 123456
@productId1 = 1
@productId2 = 2
@productId3 = 3


### 1. 管理员登录
POST {{baseUrl}}/api/admin/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "{{password}}"
}

> {%
    client.test("管理员登录成功", function () {
        client.assert(response.status === 200);
        client.assert(response.body.code === 200);
    });

    client.global.set(
        "adminToken",
        response.body.data.token
    );
%}

### 2. 查询未上架商品
GET {{baseUrl}}/api/admin/products?publishStatus=0&pageNum=1&pageSize=100
Authorization: Bearer {{adminToken}}

> {%
    client.test("查询未上架商品成功", function () {
        client.assert(response.status === 200);
        client.assert(response.body.code === 200);
    });
%}


### 3. 查看第一个商品详情，确认存在SKU
GET {{baseUrl}}/api/admin/products/{{productId1}}/detail
Authorization: Bearer {{adminToken}}

### 4. 上架第一个商品
PUT {{baseUrl}}/api/admin/products/{{productId1}}/publish-status
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "publishStatus": 1
}

> {%
    client.test("第一个商品上架成功", function () {
        client.assert(response.status === 200);
        client.assert(response.body.code === 200);
        client.assert(response.body.data.publishStatus === 1);
    });
%}

### 5. 上架第二个商品
PUT {{baseUrl}}/api/admin/products/{{productId2}}/publish-status
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "publishStatus": 1
}

### 6. 上架第三个商品
PUT {{baseUrl}}/api/admin/products/{{productId3}}/publish-status
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "publishStatus": 1
}